# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "svn-hook-tools"
  s.version = "0.5.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["crazycode"]
  s.date = "2012-01-04"
  s.description = "svn jira hook ruby lib."
  s.email = "crazycode@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "lib/jira4r/jira4r.rb",
    "lib/jira4r/jira_tool.rb",
    "lib/jira4r/v2/JiraSoapServiceDriver.rb",
    "lib/jira4r/v2/jiraService.rb",
    "lib/jira4r/v2/jiraServiceMappingRegistry.rb",
    "lib/jiraService.rb",
    "lib/jiraServiceMappingRegistry.rb",
    "lib/svn_hook_tools.rb",
    "lib/svn_jira_hook.rb",
    "pre-commit.sample",
    "svn-hook-tools.gemspec",
    "test/config/svn_hooks.yml",
    "test/test_helper.rb",
    "test/test_jira.rb"
  ]
  s.homepage = "http://github.com/crazycode/svn-hooks"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "svn jira hook lib."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubyjedi-soap4r>, ["~> 1.5.8.20100619003610"])
    else
      s.add_dependency(%q<rubyjedi-soap4r>, ["~> 1.5.8.20100619003610"])
    end
  else
    s.add_dependency(%q<rubyjedi-soap4r>, ["~> 1.5.8.20100619003610"])
  end
end

